### ISSUE TITLE
Deleting Posts

### ISSUE THREAD

**Issue by MikeNGarrett** [TrsstProject/trsst#17]
Not exactly a bug, but is the intention to still show some meta data to the public about posts that have been deleted? 

See the bottom of my page: http://home.trsst.com/EHGXT1tk33vKVS86MRkWvL3XhE46iAxkb

The only thing that seems to be showing up is the timestamp and the fact that something used to be there.

**Comment by mmpowers** [comment]
Yes, this is by design.  Part of what we're trying to solve is the problem of internet censorship, where an attacker would omit the transfer of certain objectionable entries without you knowing about it, and our "blogchain" of digital signatures solves this.  The tradeoff is that in the case of a delete, we have to have a placeholder there saying that there was an entry here (preserving the signature chain), and a new  "tombstone" entry proving that you were the one that deleted it.  

Deletes are rare enough that it doesn't overly pollute your feed, and clients can choose to display or hide those entries as they wish.  

One incidental advantage to proof-of-deletion, when combined with your copyright over your posts, is that you can exercise your rights against someone who copies and distributes your deleted post.  Copyrighted tweets are still a legal gray area, and there's still broad latitude for fair-use, but this gives you a leg to stand on if you "accidentally" post  and delete embarrassing things that another site decides to publish for their own profit.

**Comment by MikeNGarrett** [comment]
Both the chain and the proof-of-deletion make a lot of sense here. Thanks for the explanation!
